// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDDHTga-2itG19DVyn65YEAqziSwII5Ys8",
      authDomain: "emallbazar-customer.firebaseapp.com",
      projectId: "emallbazar-customer",
      storageBucket: "emallbazar-customer.firebasestorage.app",
      messagingSenderId: "782690703948",
      appId: "1:782690703948:web:616ca9dfb4f8f18fe472e9",
      measurementId: "G-6HJ3270BY3"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcut1Ba41Fzxy3nAjLDtKmhJy2D5AkZRg',
    appId: '1:782690703948:android:faa38b6be4760eb5e472e9',
    messagingSenderId: '782690703948',
    projectId: 'emallbazar-customer',
    storageBucket: 'emallbazar-customer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBusENYY_9QM5nLi3lMJaCaECAJB2W-LhA',
    appId: '1:327324836622:ios:f4c05db96aa86bc636ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    storageBucket: 'eshop-multivendor-new.appspot.com',
    androidClientId: '327324836622-0da9k42bkpmfgjbkji5a9l2lq37g0tvr.apps.googleusercontent.com',
    iosClientId: '327324836622-66keg8mgjde4hdd1g14uee9hbks5ngki.apps.googleusercontent.com',
    iosBundleId: 'wrteam.eshop.multivendor',
  );
}
