// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAXLmPO0ZOT3ycpW4ize89_Tf4Aae6P4jQ",
      authDomain: "emallbazar-faf7d.firebaseapp.com",
      projectId: "emallbazar-faf7d",
      storageBucket: "emallbazar-faf7d.firebasestorage.app",
      messagingSenderId: "849851412093",
      appId: "1:849851412093:web:36f30b1f35d0f5e31b8b14",
      measurementId: "G-P1Q754925Z"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7n45qqMW286D165Xq7mHHHaqYkOiR0',
    appId: '1:849851412093:android:b985c8e5115b2bbf1b8b14',
    messagingSenderId: '849851412093',
    projectId: 'emallbazar-faf7d',
    storageBucket: 'emallbazar-faf7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBusENYY_9QM5nLi3lMJaCaECAJB2W-LhA',
    appId: '1:327324836622:ios:f4c05db96aa86bc636ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    storageBucket: 'eshop-multivendor-new.appspot.com',
    androidClientId: '327324836622-0da9k42bkpmfgjbkji5a9l2lq37g0tvr.apps.googleusercontent.com',
    iosClientId: '327324836622-66keg8mgjde4hdd1g14uee9hbks5ngki.apps.googleusercontent.com',
    iosBundleId: 'wrteam.eshop.multivendor',
  );
}
